pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'cd src && ./gradlew build --no-daemon'
            }
        }

        stage('Test') {
            steps {
                sh 'cd src && ./gradlew test --no-daemon'
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts 'src/app/build/libs/app.jar'
            }
        }
    }
}